export default function DisclaimerPage() {
  return (
    <article className="prose prose-invert prose-sm max-w-none text-uc-gray-300 leading-relaxed">
      <h1 className="text-2xl font-bold text-white tracking-tight mb-1">
        Platform Disclaimer
      </h1>
      <p className="text-xs text-uc-gray-500 mb-8">
        Last Updated: June 2025
      </p>

      {/* Critical Notice */}
      <div className="bg-uc-surface border border-uc-cyan/20 rounded-lg p-5 mb-8">
        <p className="text-sm text-white font-semibold mb-2">
          Important Notice
        </p>
        <p className="text-sm text-uc-gray-300 leading-relaxed">
          Under Center is a technology platform. We are not a law firm,
          accounting firm, financial advisory firm, or compliance consultancy.
          Nothing on this Platform constitutes legal, tax, financial, or
          compliance advice. All content is provided for educational and
          informational purposes only.
        </p>
      </div>

      {/* 1 */}
      <h2 className="text-lg font-semibold text-white mt-10 mb-3">
        1. Educational Purpose
      </h2>
      <p>
        All content on the Under Center platform — including but not limited to
        NIL state law summaries, compliance matrices, valuation estimates,
        agreement templates, resource articles, and marketplace tools — is
        designed to assist users in understanding Name, Image, and Likeness
        concepts. This content is intended to support independent
        decision-making, not to replace professional counsel.
      </p>

      {/* 2 */}
      <h2 className="text-lg font-semibold text-white mt-10 mb-3">
        2. No Attorney-Client Relationship
      </h2>
      <p>
        Use of this Platform does not create an attorney-client, fiduciary, or
        advisory relationship between you and Under Center. We do not provide
        legal opinions, regulatory interpretations, or compliance certifications.
        Users should consult qualified professionals for legal, tax, and
        regulatory matters specific to their circumstances.
      </p>

      {/* 3 */}
      <h2 className="text-lg font-semibold text-white mt-10 mb-3">
        3. State Law Information
      </h2>
      <p>
        State NIL law data presented on the Platform, including the compliance
        matrix and state-specific summaries, reflects our understanding of
        publicly available information at the time of publication. NIL
        legislation is rapidly evolving. Laws may have changed since our last
        update. We do not guarantee the accuracy, completeness, or currency of
        any state law information. Users are solely responsible for verifying
        applicable law in their jurisdiction.
      </p>

      {/* 4 */}
      <h2 className="text-lg font-semibold text-white mt-10 mb-3">
        4. Valuation Estimates
      </h2>
      <p>
        NIL valuation figures generated by the Platform are preliminary
        estimates based on algorithmic models using publicly available data
        points. These estimates are provided for educational reference only and
        should not be relied upon as market valuations, appraisals, or
        guarantees of earning potential. Actual NIL market value depends on
        numerous factors not captured by any algorithm.
      </p>

      {/* 5 */}
      <h2 className="text-lg font-semibold text-white mt-10 mb-3">
        5. Agreement Templates
      </h2>
      <p>
        Agreement templates and draft structures available on the Platform are
        educational examples intended to illustrate common NIL agreement
        provisions. They have not been reviewed by an attorney for your
        specific situation. These templates should not be executed without
        review and customization by qualified legal counsel. Under Center
        assumes no liability for any use of template content.
      </p>

      {/* 6 */}
      <h2 className="text-lg font-semibold text-white mt-10 mb-3">
        6. NCAA and Governing Body Compliance
      </h2>
      <p>
        The Platform does not certify compliance with NCAA, NAIA, NJCAA, or any
        conference or institutional rules. Compliance determinations are the
        sole responsibility of the applicable governing body and the
        institution&apos;s compliance office. Under Center&apos;s tools are
        designed to assist users in organizing information — not to provide
        compliance approval.
      </p>

      {/* 7 */}
      <h2 className="text-lg font-semibold text-white mt-10 mb-3">
        7. Third-Party Content
      </h2>
      <p>
        The Platform may display or link to content provided by third parties,
        including recruiting data, social media metrics, and brand offers. We
        do not endorse, verify, or assume responsibility for the accuracy or
        legality of third-party content.
      </p>

      {/* 8 */}
      <h2 className="text-lg font-semibold text-white mt-10 mb-3">
        8. No Guarantees
      </h2>
      <p>
        Under Center does not guarantee any particular outcome from use of the
        Platform, including but not limited to: NIL deal completion, revenue
        generation, compliance status, recruiting interest, or brand
        partnership formation. Past performance data displayed on the Platform
        is not indicative of future results.
      </p>

      {/* 9 */}
      <h2 className="text-lg font-semibold text-white mt-10 mb-3">
        9. Limitation of Reliance
      </h2>
      <p>
        You acknowledge that any reliance on information provided through the
        Platform is at your own risk. Under Center expressly disclaims all
        liability arising from your reliance on Platform content or any actions
        taken based on such content.
      </p>

      {/* 10 */}
      <h2 className="text-lg font-semibold text-white mt-10 mb-3">
        10. Contact
      </h2>
      <p>
        If you have questions about this Disclaimer, contact us at{" "}
        <span className="text-uc-cyan">legal@undercenter.com</span>.
      </p>
    </article>
  );
}
