import type { Athlete } from "./store";

export const PLACEHOLDER_ATHLETES: Athlete[] = [
  {
    id: "1",
    name: "Jaxon Smith",
    gradYear: 2026,
    position: "QB",
    height: "6'3\"",
    weight: 205,
    state: "Texas",
    school: "Westlake High School",
    photoUrl: "/athletes/placeholder-1.jpg",
    verified: true,
    rating: 4.5,
    qbClass: "Pro-Style",
    metrics: {
      velocity: 61.8,
      releaseTime: 0.38,
      spinRate: 680,
      mechanics: 92,
      accuracy: 88,
      decisionSpeed: 85,
    },
    offers: ["Alabama", "Ohio State", "Georgia", "Texas", "USC"],
    filmUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    comparisonPlayer: "Patrick Mahomes",
  },
  {
    id: "2",
    name: "Marcus Rivera",
    gradYear: 2026,
    position: "QB",
    height: "6'1\"",
    weight: 195,
    state: "California",
    school: "Mater Dei High School",
    photoUrl: "/athletes/placeholder-2.jpg",
    verified: true,
    rating: 4.0,
    qbClass: "Dual-Threat",
    metrics: {
      velocity: 58.2,
      releaseTime: 0.41,
      spinRate: 620,
      mechanics: 85,
      accuracy: 90,
      decisionSpeed: 92,
    },
    offers: ["Oregon", "USC", "Miami", "LSU"],
    filmUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    comparisonPlayer: "Lamar Jackson",
  },
  {
    id: "3",
    name: "Tyler Washington",
    gradYear: 2027,
    position: "QB",
    height: "6'4\"",
    weight: 215,
    state: "Georgia",
    school: "Buford High School",
    photoUrl: "/athletes/placeholder-3.jpg",
    verified: false,
    rating: 3.5,
    qbClass: "Pro-Style",
    metrics: {
      velocity: 55.0,
      releaseTime: 0.44,
      spinRate: 560,
      mechanics: 78,
      accuracy: 82,
      decisionSpeed: 79,
    },
    offers: ["Georgia", "Auburn"],
    comparisonPlayer: "Justin Herbert",
  },
  {
    id: "4",
    name: "Dylan Park",
    gradYear: 2026,
    position: "QB",
    height: "6'2\"",
    weight: 200,
    state: "Ohio",
    school: "Archbishop Moeller",
    photoUrl: "/athletes/placeholder-4.jpg",
    verified: true,
    rating: 4.0,
    qbClass: "Pocket Passer",
    metrics: {
      velocity: 60.1,
      releaseTime: 0.36,
      spinRate: 650,
      mechanics: 89,
      accuracy: 91,
      decisionSpeed: 87,
    },
    offers: ["Ohio State", "Notre Dame", "Michigan", "Penn State", "Clemson"],
    filmUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    comparisonPlayer: "Joe Burrow",
  },
  {
    id: "5",
    name: "Kai Nakamura",
    gradYear: 2027,
    position: "QB",
    height: "6'0\"",
    weight: 185,
    state: "Hawaii",
    school: "Saint Louis School",
    photoUrl: "/athletes/placeholder-5.jpg",
    verified: true,
    rating: 3.5,
    qbClass: "Dual-Threat",
    metrics: {
      velocity: 56.5,
      releaseTime: 0.42,
      spinRate: 590,
      mechanics: 81,
      accuracy: 86,
      decisionSpeed: 90,
    },
    offers: ["Oregon", "Washington", "UCLA"],
    comparisonPlayer: "Marcus Mariota",
  },
  {
    id: "6",
    name: "Andre Mitchell",
    gradYear: 2026,
    position: "QB",
    height: "6'5\"",
    weight: 225,
    state: "Florida",
    school: "IMG Academy",
    photoUrl: "/athletes/placeholder-6.jpg",
    verified: true,
    rating: 5.0,
    qbClass: "Pro-Style",
    metrics: {
      velocity: 63.4,
      releaseTime: 0.35,
      spinRate: 710,
      mechanics: 95,
      accuracy: 93,
      decisionSpeed: 91,
    },
    offers: [
      "Alabama",
      "Georgia",
      "Ohio State",
      "Clemson",
      "Texas",
      "USC",
      "Oregon",
      "Notre Dame",
    ],
    filmUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    comparisonPlayer: "Trevor Lawrence",
  },
];
